CREATE DATABASE M07_UF3;
USE M07_UF3;

CREATE TABLE ESTADISTIQUES (
ID INT PRIMARY KEY NOT NULL,
MODALITAT VARCHAR (45) NOT NULL,
NIVELL INT DEFAULT (1),
DATA_USUARI DATE DEFAULT CURRENT_TIMESTAMP,
INTENTS INT DEFAULT (0)
);